name: Collect Exchange Info
on:
  repository_dispatch:
    types: [exchange]

jobs:
  exchange:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Run binary
        run: ./bin/exchange
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_AUTH_TOKEN: ${{ secrets.DB_AUTH_TOKEN }}
          POE_AUTH_TOKEN: ${{ secrets.POE_AUTH_TOKEN }}
